name: Build Repo

on:
  push:
    branches: [ main ]

permissions:
  contents: write  # 允许 Actions 写仓库

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dpkg-dev
        run: |
          sudo apt update
          sudo apt install -y dpkg-dev

      - name: Generate Packages and Release
        run: |
          mkdir -p debs
          dpkg-scanpackages ./debs /dev/null > Packages
          gzip -k -f Packages

          cat <<EOF > Release
Origin: LDPPKONG Repo
Label: LDPPKONG Repo
Suite: stable
Version: 1.0
Codename: ios
Architectures: iphoneos-arm64
Components: main
Description: LDPPKONG Jailbreak Repo
EOF

      - name: Commit and Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Packages Packages.gz Release
          git diff --cached --quiet && echo "No changes to commit." || git commit -m "Update Packages"
          git push
